wip

diff --git a/scan_postprocessing b/scan_postprocessing
--- a/scan_postprocessing
+++ b/scan_postprocessing
@@ -2,83 +2,41 @@
 
 DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
-DEVICE=fujitsu
-OUTPUT=scan.pdf
-OUTPUTARR=()
-USEOUTPUT=0
-USEARRAY=0
-APPEND=0
+VERBOSE=0
 RESOLUTION=300
-MODE=Lineart
-MODE_CHANGED=0
-MODE_HW_DEFAULT=0
-SCRIPT="$DIR/scan_perpage"
-DUPLEX=0
+APPEND=0
+MAXPAGE=
+TRUNCPAGE=0
 UNPAPER=0
 SEARCHABLE=0
 LANGUAGE=eng
-MAXPAGE=
-TRUNCPAGE=0
-HELP=0
-SIZE=
-DEFAULTSIZE=1
-PGHEIGHT=
-PGHEIGHTIN=
-PGWIDTH=
-PGWIDTHIN=
-CROP=0
-DESKEW=0
-DRIVER_OPTION=
-VERBOSE=0
 SKIP_EMPTY_PAGES=0
-OPTIMIZE_IMAGES=0
-FULL_OPTIMIZATION=0
-SOURCE=""
+OPTIMIZATION=
+PAGE_WIDTH=
+PAGE_HEIGHT=
+PS2PDF_OPTS=
+INPUT_DIR=
+OUTPUT=
 
-TMP_DIR=$(mktemp -d -p "" scan.XXXXXXXXXX)
 cleanup()
 {
-  rm -rf "$TMP_DIR"
+  rm -rf "$INPUT_DIR"
 }
 trap cleanup EXIT
-
-DEFAULTS="${XDG_DATA_HOME:-$HOME/.local/share}/sane-scan-pdf/defaults"
-SCANPRE="${XDG_DATA_HOME:-$HOME/.local/share}/sane-scan-pdf/scan_pre"
-[ -e "$DEFAULTS" ] && . "$DEFAULTS"
 
 # Parse command-line options
 while [[ $# > 0 ]]; do
   case "$1" in
 
-  -v|--verbose) VERBOSE=1 ;;
+  --verbose) VERBOSE=1 ;;
 
-  -d|--duplex) DUPLEX=1 ;;
+  --resolution) shift; RESOLUTION=$1 ;;
 
-  -m|--mode) shift; MODE=$1; MODE_CHANGED=1 ;;
+  --append) APPEND=1 ;;
 
-  --mode-hw-default) MODE_HW_DEFAULT=1 ;;
+  --max) shift; MAXPAGE=$1 ;;
 
-  -r|--resolution) shift; RESOLUTION=$1 ;;
-
-  -a|--append) APPEND=1 ;;
-
-  -e|--max) shift; MAXPAGE=$1 ;;
-
-  -t|--truncate) shift; TRUNCPAGE=$1 ;;
-
-  -h|--help) HELP=1 ;;
-
-  -s|--size) shift; SIZE=$1 ;;
-
-  -ph|--page-height) shift; PGHEIGHT=$1 ;;
-
-  -pw|--page-width) shift; PGWIDTH=$1 ;;
-
-  --no-default-size) DEFAULTSIZE=0 ;;
-
-  --crop) CROP=1 ;;
-
-  --deskew) DESKEW=1 ;;
+  --truncate) shift; TRUNCPAGE=$1 ;;
 
   --unpaper) UNPAPER=1 ;;
 
@@ -88,228 +46,142 @@ while [[ $# > 0 ]]; do
 
   --skip-empty-pages) SKIP_EMPTY_PAGES=1 ;;
 
-  --optimize-images) OPTIMIZE_IMAGES=1 ;;
+  --optimization) OPTIMIZATION=$1 ;;
 
-  --full-optimization) FULL_OPTIMIZATION=1 ;;
+  --page-width) PAGE_WIDTH=$1 ;;
 
-  -o|--output) shift; USEOUTPUT=1; OUTPUT="$1" ;;
+  --page-height) PAGE_HEIGHT=$1 ;;
 
-  -l|--outputlist) shift; USEARRAY=1; OUTPUTARR=(); OUTPUTARR+=("$1") ;;
+  --ps2pdf-opts) PS2PDF_OPTS=$1 ;;
 
-  -x|--device) shift; DEVICE="$1";;
+  --input-dir) shift; INPUT_DIR="$1" ;;
 
-  -xo|--driver-options) shift; DRIVER_OPTION=$1;;
+  --output) shift; OUTPUT="$1" ;;
 
-  *) if [[ $USEARRAY == 1 ]]; then OUTPUTARR+=("$1"); else echo >&2 "Unknown argument: $1"; exit 1; fi ;;
+  *) echo >&2 "Unknown argument: $1"; exit 1 ;;
 
   esac
   shift   # next option
 done
 
-if [[ $HELP == 1 ]]; then
-  echo "$(basename $0) [OPTIONS]... [OUTPUT]"
-  echo ""
-  echo "OPTIONS"
-  echo " -v, --verbose"
-  echo "   Verbose output (this will slow down the scan due to the need to prevent interleaved output)"
-  echo " -d, --duplex"
-  echo "   Duplex scanning"
-  echo " -m, --mode"
-  echo "   Mode e.g. Lineart (default), Halftone, Gray, Color, etc. Use --mode-hw-default to not set any mode"
-  echo " --mode-hw-default"
-  echo "   Do not set the mode explicitly, use the hardware default"
-  echo " -r, --resolution"
-  echo "   Resolution e.g 300 (default)"
-  echo " -a, --append"
-  echo "   Append output to existing scan"
-  echo " -e, --max <pages>"
-  echo "   Max number of pages e.g. 2 (default is all pages)"
-  echo " -t, --truncate <pages>"
-  echo "   Truncate number of pages from end e.g. 1 (default is none) -- truncation happens after --skip-empty-pages"
-  echo " -s, --size"
-  echo "   Page Size as type e.g. Letter (default), Legal, A4, no effect if --crop is specified"
-  echo " -ph, --page-height"
-  echo "   Custom Page Height in mm"
-  echo " -pw, --page-width"
-  echo "   Custom Page Width in mm"
-  echo " -x, --device"
-  echo "  Override scanner device name, defaulting to \"$DEVICE\""
-  echo " -xo, --driver-options"
-  echo "  Send additional options to the scanner driver e.g."
-  echo "  -xo \"--whatever bar --frobnitz baz\""
-  echo " --no-default-size"
-  echo "   Disable default page size, useful if driver does not support page size/location arguments"
-  echo " --crop"
-  echo "   Crop to contents (driver must support this)"
-  echo " --deskew"
-  echo "   Run driver deskew (driver must support this)"
-  echo " --unpaper"
-  echo "   Run post-processing deskew and black edge detection (requires unpaper)"
-  echo " --ocr"
-  echo "   Run OCR to make the PDF searchable (requires tesseract)"
-  echo " --language <lang>"
-  echo "   Which language to use for OCR"
-  echo " --skip-empty-pages"
-  echo "   Remove empty pages from resulting PDF document (e.g. one sided doc in duplex mode)"
-  echo " --optimize-images"
-  echo "   Runs an ImageMagick optimization script that should produce cleaner scans. "
-  echo " --full-optimization"
-  echo "   Uses another, more agressive, algorithm to clean up the images. It produces excellent results when dealing with documents but will tend to destroy contained photos. "
-  echo "OUTPUT"
-  echo " -o, --output <outputfile>"
-  echo "   Output to named file default=scan.pdf"
-  echo " -l, --outputlist <outputfile-1...outputfile-n> Output to named files for each scanned page, can be used with append"
-  echo ""
-  echo "CONFIGURATION"
-  echo "Local configuration can be written in the form of environment variables to:"
-  echo "  $DEFAULTS"
-  echo ""
-  echo "A pre-scan hook script can be written to:"
-  echo "  $SCANPRE"
-  echo ""
-  exit 0
-fi
+log()
+{
+  if [[ $VERBOSE == 1 ]]; then
+    echo "scan_postprocessing: $1"
+  fi
+}
 
-if [[ $USEARRAY == 1 && $USEOUTPUT == 1 ]]; then
-  echo >&2 "Use one of -o or -l. Aborting."
-  exit 1
-fi
+logstdout()
+{
+  if [[ $VERBOSE == 1 ]]; then
+    cat
+  else
+    cat > /dev/null
+  fi
+}
 
-if [[ $MODE_CHANGED == 1 && $MODE_HW_DEFAULT == 1 ]]; then
-  echo >&2 "Use one of -m/--mode or --mode-hardware-default. Aborting."
-  exit 1
-fi
+runconstrained()
+{
+  if [[ -x "$(command -v sem)" ]]; then
+    # use up to 75% of the cores available
+    arg=$(echo "$@" | sed -E 's/([\(\)])/\\\1/g')  # Escaping parenthesis, otherwise the following will fail
+    sem --jobs 75% --id scan_postprocessing --fg "$arg"
+  else
+    "$@"
+  fi
+}
 
-if [[ $MODE_CHANGED == 0 && $MODE_HW_DEFAULT == 0 ]]; then
-  echo >&2 'Warning: neither the -m/--mode nor --mode-hw-default argument was specified. The current default is "Lineart", however -m/--mode is a SANE device-specific switch. Therefore, in a future version when --mode is not specified, `'"`basename "$0"`""'"' will defer to the device-specific default. If you wish to continue using "Lineart" as your scan mode, either verify that is the default for your scanner (scanadf --help -d <device>), or specify --mode Lineart explicitly on the command line.'
-fi
-
-if [[ $USEOUTPUT == 1 && "$OUTPUT" == "" ]]; then
-  echo >&2 "Output file must be specified. Aborting."
-  exit 1
-fi
-
-if [[ $USEOUTPUT == 1 && -f "$OUTPUT" && $APPEND != 1 ]]; then
-  echo >&2 "Output file $OUTPUT already exists. Delete or specify -a. Aborting."
-  exit 1
-fi
-
-if [[ $USEARRAY == 1 && ${#OUTPUTARR[@]} == 0 ]]; then
-  echo >&2 "At least one file must be specified with -l. Aborting."
-  exit 1
-fi
-
-if [[ $USEARRAY == 1 && $APPEND != 1 ]]; then
-  for o in "${OUTPUTARR[@]}"; do
-    if [[ -f "$o" ]]; then
-      echo >&2 "Output file $o already exists. Delete or specify -a. Aborting."
-      exit 1
-    fi
-  done
-fi
-
-if [[ $USEARRAY == 1 ]]; then
-  OUTPUT=("${OUTPUTARR[@]}")
-fi
-
-if [[ $DUPLEX == 1 ]]; then
-  SOURCE="--source \"ADF Duplex\""
-fi
-
-if [[ "$MAXPAGE" != "" ]]; then
-  MAXPAGE="-e $MAXPAGE"
-fi
-
-PS2PDF_OPTS=
-
-if [[ $CROP != 1 && $SIZE == "" && $DEFAULTSIZE == 1 ]]; then
-  # Default to Letter size, but only if crop is not specified and this feature is not disabled
-  SIZE=Letter
-fi
-
-case "$SIZE" in
-
-  Letter) PGHEIGHT=279.4; PGWIDTH=215.9 ;;
-
-  Legal) PGHEIGHT=355.6; PGWIDTH=215.9 ;;
-
-  A4) PGHEIGHT=297; PGWIDTH=210 ;;
-
-esac
-
-if [[ $CROP != 1 && "$PGHEIGHT" != "" ]]; then
-  PGHEIGHTIN=$(units --compact -1 "$PGHEIGHT mm" 'in')
-  PGHEIGHT="--page-height $PGHEIGHT -y $PGHEIGHT"
-  PS2PDF_OPTS="-dEPSCrop"
-fi
-
-if [[ $CROP != 1 && "$PGWIDTH" != "" ]]; then
-  PGWIDTHIN=$(units --compact -1 "$PGWIDTH mm" 'in')
-  PGWIDTH="--page-width $PGWIDTH -x $PGWIDTH"
-  PS2PDF_OPTS="-dEPSCrop"
-fi
-
-if [[ $CROP == 1 ]]; then
-  CROP="--swcrop=yes --ald=yes"
-  # In duplex mode, the driver's buffer for the back side image will be larger than necessary, oh well
-  # http://sane.10972.n7.nabble.com/Fujitsu-backend-and-iX500-scanning-page-longer-than-14-Inches-td19303.html
-  PGHEIGHT="--page-height 9999 -y 9999"
-  PGWIDTH="--page-width 9999 -x 9999"
-  PS2PDF_OPTS="-dEPSCrop"
-fi
-
-if [[ $DESKEW == 1 ]]; then
-  DESKEW="--swdeskew=yes"
-fi
-
-if [[ $SKIP_EMPTY_PAGES == 1 && ! -x "$(command -v bc)" ]]; then
-  echo >&2 'Warning: `--skip-empty-pages` specified, but `bc` not available. Disabling empty page detection.'
-  SKIP_EMPTY_PAGES=0
-fi
-
-if [[ $OPTIMIZE_IMAGES == 1 ]]; then
-    OPTIMIZE_IMAGES="STD"
-    if [[ $FULL_OPTIMIZATION == 1 ]]; then
-        OPTIMIZE_IMAGES="FULL"
-    fi
-else
-    OPTIMIZE_IMAGES="NONE"
-    if [[ $FULL_OPTIMIZATION == 1 ]]; then
-        echo >&2 'Warning: `--full-optimization` specified, without `--optimize-images`. No optimization will be done.'
-    fi
-fi
-
-export VERBOSE
-export UNPAPER
-export SEARCHABLE
-export LANGUAGE
-export RESOLUTION
-export PGWIDTHIN
-export PGHEIGHTIN
-export PS2PDF_OPTS
-export SKIP_EMPTY_PAGES
-export OPTIMIZE_IMAGES
-
+TIMEVERBOSE=
 if [[ $VERBOSE == 1 ]]; then
-  LOCKFILE=$(mktemp)
-  trap "cleanup; rm -rf $LOCKFILE" EXIT
-  export LOCKFILE
-fi;
-
-echo >&2 "Scanning..."
-#eval strace -f -o /tmp/scan-trace.txt scanadf -d $DEVICE $MAXPAGE $PGHEIGHT $PGWIDTH -S $SCRIPT --script-wait --resolution $RESOLUTION --mode $MODE $DESKEW $CROP $SOURCE -o scan-%04d
-if [[ $MODE_HW_DEFAULT == 1 ]]; then
-  MODE=
-else
-  MODE="--mode '$MODE'"
+  TIMEVERBOSE=time
 fi
-[ -e "$SCANPRE" ] && . "$SCANPRE"
-eval scanadf -d \'"$DEVICE"\' $MAXPAGE $PGHEIGHT $PGWIDTH -S $SCRIPT --script-wait $DESKEW $CROP $DRIVER_OPTION $SOURCE --resolution $RESOLUTION $MODE -o $TMP_DIR/scan-%04d
-# Simulate empty page scanner outputs for debugging
-#convert xc:none -page Letter $TMP_DIR/scan-0001.pdf
 
 shopt -s extglob nullglob
-pdffiles=($TMP_DIR/scan-[0-9]*.pdf)
+ppmfiles=($INPUT_DIR/scan-[0-9]*)
+numscans=${#ppmfiles[@]}
+if (( numscans == 0 )); then
+  echo "Found no scans."
+  exit 1
+fi
+
+for x in ${ppmfiles[@]}; do
+  IMAGE_PATH=$x
+  IMAGE_DIR=$(dirname $x)
+  IMAGE_FILE=$(basename $x)
+
+  if [[ $SKIP_EMPTY_PAGES == 1 ]]; then
+    PERCENTAGE_WHITE=$(convert "$IMAGE_PATH" -resize 20% -shave 4%x4% \( +clone -lat ${RESOLUTION/5}x${RESOLUTION/5}-10% -threshold 96% \) -compose lighten -composite -fuzz 0% -negate -threshold 0 -negate -format "%[fx:100*mean]" info:) || PERCENTAGE_WHITE=0
+    log "$IMAGE_PATH has $PERCENTAGE_WHITE % white"
+  else
+    PERCENTAGE_WHITE=0
+  fi
+
+  if [[ $SKIP_EMPTY_PAGES == 1 && $(echo "$PERCENTAGE_WHITE > 99.8" | bc -l) == 1 ]]; then
+    log "Skipping empty page $IMAGE_FILE with white percentage $PERCENTAGE_WHITE"
+  else
+    if [[ "$OPTIMIZE_IMAGES" == "std" ]]; then
+      log "Applying optimization script \"$OPTIMIZE_IMAGES\" to image data..."
+      runconstrained $TIMEVERBOSE convert $IMAGE_PATH -level 8%,90% -fuzz 8% -fill white -opaque "rgb(255, 255, 255)" $IMAGE_PATH | logstdout
+    fi
+
+    if [[ "$OPTIMIZE_IMAGES" == "full" ]]; then
+      log "Applying optimization script \"$OPTIMIZE_IMAGES\" to image data..."
+      runconstrained $TIMEVERBOSE convert $IMAGE_PATH \( +clone -lat ${RESOLUTION}x${RESOLUTION}-10% -threshold 96% \) -compose lighten -composite $IMAGE_PATH | logstdout
+    fi
+
+    if [[ $UNPAPER == 1 ]]; then
+      log "Applying unpaper post-processing to image data..."
+      PP_PREFIX="unpaper-"
+      if [[ $VERBOSE == 1 ]]; then
+        UNPAPERVERBOSE="-v"
+      fi
+      #runconstrained $TIMEVERBOSE unpaper $UNPAPERVERBOSE --no-mask-scan --overwrite --dpi $RESOLUTION --no-blackfilter $IMAGE_FILE $PP_PREFIX$IMAGE_FILE | logstdout
+      runconstrained $TIMEVERBOSE unpaper $UNPAPERVERBOSE --overwrite --dpi $RESOLUTION $IMAGE_PATH $IMAGE_DIR/$PP_PREFIX$IMAGE_FILE | logstdout
+    fi
+
+    if [[ $SEARCHABLE == 1 ]]; then
+      log "Converting image data to searchable pdf..."
+      # tesseract uses the input's DPI header, we need to convert to a format that supports this (like tiff)
+      log "...Running convert"
+      runconstrained $TIMEVERBOSE convert -density ${RESOLUTION}x${RESOLUTION} -units PixelsPerInch $IMAGE_DIR/$PP_PREFIX$IMAGE_FILE $IMAGE_DIR/$PP_PREFIX${IMAGE_FILE}.tiff | logstdout
+      log "...Running tesseract"
+      runconstrained $TIMEVERBOSE tesseract $IMAGE_DIR/$PP_PREFIX${IMAGE_FILE}.tiff $IMAGE_DIR/${IMAGE_FILE%.*} -l $LANGUAGE pdf | logstdout
+      [[ -f $IMAGE_DIR/$PP_PREFIX${IMAGE_FILE}.tiff ]] && rm $IMAGE_DIR/$PP_PREFIX${IMAGE_FILE}.tiff
+    else
+      log "Converting image data to pdf..."
+      if [[ "$PGWIDTHIN" == "" || "$PGHEIGHTIN" == "" ]]; then
+        PAGEOPTS="-equalpixels -dpi=$RESOLUTION -noturn"
+      else
+        PAGEOPTS="-imagewidth $PGWIDTHIN -imageheight $PGHEIGHTIN"
+      fi
+      PNMVERBOSE=
+      # older versions of pnmtops (Ubuntu, Debian) don't have the -verbose option, test for it
+      if [[ $VERBOSE == 1 && ! "$(pnmtops -verbose 2>&1 < /dev/null)" =~ "unrecognized option" ]]; then
+        PNMVERBOSE="-verbose"
+      fi
+
+      log "...Running pnmtops on $IMAGE_DIR/$PP_PREFIX$IMAGE_FILE using page options: $PAGEOPTS"
+      runconstrained $TIMEVERBOSE pnmtops $PNMVERBOSE $PAGEOPTS $IMAGE_DIR/$PP_PREFIX$IMAGE_FILE > $IMAGE_DIR/${IMAGE_FILE}.ps | logstdout
+
+      log "...Running ps2pdf on $IMAGE_DIR/${IMAGE_FILE}.ps"
+      runconstrained $TIMEVERBOSE ps2pdf14 $PS2PDF_OPTS $IMAGE_DIR/${IMAGE_FILE}.ps $IMAGE_DIR/${IMAGE_FILE}.pdf | logstdout
+      [[ -f $IMAGE_DIR/${IMAGE_FILE}.ps ]] && rm $IMAGE_DIR/$PP_PREFIX${IMAGE_FILE}.ps
+    fi
+  fi
+
+  status=$?
+  rm $IMAGE_PATH
+  [[ -f $IMAGE_DIR/$PP_PREFIX${IMAGE_FILE} ]] && rm $IMAGE_DIR/$PP_PREFIX${IMAGE_FILE}
+
+  log ""
+  log "Scan page processing done, status = $status"
+done;
+
+
+exit 1
+
+shopt -s extglob nullglob
+pdffiles=($INPUT_DIR/scan-[0-9]*.pdf)
 numscans=${#pdffiles[@]}
 if (( numscans > 0 )); then
   echo "Processing $numscans pages"
@@ -340,13 +212,13 @@ if (( numscans > 0 )); then
           if [[ -f "${OUTPUT[$index]}.orig" ]]; then
             pdffiles+=("${OUTPUT[$index]}.orig")
           fi
-          pdffiles+=($TMP_DIR/scan-*(0)$scanno.pdf)
-          pdfunite "${pdffiles[@]}" "${OUTPUT[$index]}" && rm $TMP_DIR/scan-*(0)$scanno.pdf
+          pdffiles+=($INPUT_DIR/scan-*(0)$scanno.pdf)
+          pdfunite "${pdffiles[@]}" "${OUTPUT[$index]}" && rm $INPUT_DIR/scan-*(0)$scanno.pdf
         else
-          mv $TMP_DIR/scan-*(0)$scanno.pdf "${OUTPUT[$index]}"
+          mv $INPUT_DIR/scan-*(0)$scanno.pdf "${OUTPUT[$index]}"
         fi
       else
-        mv $TMP_DIR/scan-*(0)$scanno.pdf "${OUTPUT[$index]}"
+        mv $INPUT_DIR/scan-*(0)$scanno.pdf "${OUTPUT[$index]}"
       fi
       let "index = index + 1"
     done
@@ -359,13 +231,13 @@ if (( numscans > 0 )); then
     if [[ -f "${OUTPUT}.orig" ]]; then
       pdffiles+=("${OUTPUT}.orig")
     fi
-    pdffiles+=($TMP_DIR/scan-[0-9]*.pdf)
-    pdfunite "${pdffiles[@]}" "$OUTPUT" && rm $TMP_DIR/scan-[0-9]*.pdf
+    pdffiles+=($INPUT_DIR/scan-[0-9]*.pdf)
+    pdfunite "${pdffiles[@]}" "$OUTPUT" && rm $INPUT_DIR/scan-[0-9]*.pdf
   else
     if [[ $USEARRAY == 1 ]]; then
-      mv $TMP_DIR/scan-0*.pdf "${OUTPUT[0]}"
+      mv $INPUT_DIR/scan-0*.pdf "${OUTPUT[0]}"
     else
-      mv $TMP_DIR/scan-0*.pdf "$OUTPUT"
+      mv $INPUT_DIR/scan-0*.pdf "$OUTPUT"
     fi
   fi
   echo ""
